language: node_js
sudo: false
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
dist: trusty
node_js:
  - "7"
  - "6"
  - "6.5"

before_script:
  - npm install -g bower
  - bower install

script:
  - gulp
